# Use the official NGINX base image
FROM nginx:latest

# Copy the custom NGINX configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the entrypoint script into the container
COPY entrypoint.sh /entrypoint.sh

# Grant execute permissions to the entrypoint script
RUN chmod +x /entrypoint.sh

# Copy health check script into the container
COPY healthcheck.sh /usr/share/nginx/html/healthcheck.sh

# Set execute permissions for the health check script
RUN chmod +x /usr/share/nginx/html/healthcheck.sh

# Expose port 80 to the outside world
EXPOSE 80

# Health check configuration
HEALTHCHECK --interval=30s --timeout=3s \
  CMD /usr/share/nginx/html/healthcheck.sh

# Set the entrypoint script as the default entrypoint for the container
ENTRYPOINT ["/entrypoint.sh"]

# Define the command to start NGINX (no need to override the default CMD)
CMD ["nginx", "-g", "daemon off;"]
